language: node_js

matrix:
  include:
    - node_js: "5"
    - node_js: "4.2"

before_install:
  - npm install -g bower
  - bower install

script:
  - grunt ci
  - 'if [ "${TRAVIS_NODE_VERSION}" = "4.2" ]; then grunt protractor ; fi'